Alias onboarding analytics
planetary-social/planetary-ios pull request #1137
Opened 2023-02-01 13:14 UTC by mplorentz

#1135

2023-02-02 19:38 UTC, martindsq requested changes

2023-02-02 19:38 UTC, martindsq commented on Source/UI/RoomListView.swift
> +                        "Joining the official Planetary room server will allow to register aliases like " +
This string needs to be localized

2023-02-02 19:38 UTC, martindsq commented on Source/UI/RoomListView.swift
> +                    Button("Join Planetary Room") {
This string needs to be localized

2023-02-02 19:38 UTC, martindsq commented on Source/UI/RoomListView.swift
> +            alertMessage = "Error joining room"
This string needs to be localized

2023-02-02 19:42 UTC, martindsq commented
Just a couple of strings that need to be localized and a CHANGELOG entry is needed here to close the PR.

As a side note: I've seen that you don't use this https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue in your PR descriptions, I find them very handy to automatically link issues when opening a PR.

2023-02-08 21:21 UTC, mplorentz commented
> As a side note: I've seen that you don't use this https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue in your PR descriptions, I find them very handy to automatically link issues when opening a PR.

I probably should. I usually go back and read the ticket and comments again after I click "merge" to make sure it is ready to be closed, so I'm not thinking about closing it when I'm creating the PR. But it would probably be more clear to do it that way.

2023-02-13 18:06 UTC, merged