Fix some warnings
planetary-social/planetary-ios pull request #1274
Opened 2023-10-23 10:21 UTC by RomanPodymov

Hello.
Thank you for planetary-ios.
Fix some warnings.

2023-10-23 10:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/planetary-social/planetary-ios?pullRequest=1274) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/planetary-social/planetary-ios?pullRequest=1274) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/planetary-social/planetary-ios?pullRequest=1274) it.</sub>

2023-12-13 17:00 UTC, mplorentz requested changes
Hi @RomanPodymov, thanks so much for the contribution. I'm sorry it's take so long to get back to you, we aren't working much on Planetary anymore. 

I think you can ignore the test failures for these tests:
```
FeedStrategyTests.testPostsAlgorithm()
FeedStrategyTests.testPostsAndContactsAlgorithm()
FeedStrategyTests.testRecentlyActivePostsAndContactsAlgorithm()
```

They are also failing on `main`. However I am worried about this failing test: 
```
AppConfigurationTests.test_archiving()
```
As that one has not failed on `main`, and I suspect it may be related to the changes to `AppConfiguration+Data.swift`. If you could take a look into that I would appreciate it. Otherwise I will look into it when I get time.

2024-07-19 15:32 UTC, RomanPodymov commented
Hello @mplorentz 
Fixed `AppConfigurationTests.test_archiving`.

2024-07-24 14:19 UTC, mplorentz approved these changes
Thank you for the contribution @RomanPodymov!

2024-07-24 20:21 UTC, merged