Add Logger module
planetary-social/planetary-ios pull request #353
Opened 2022-02-10 17:47 UTC by martindsq

2022-02-10 21:13 UTC, mplorentz requested changes
Hey Martin, awesome work here. I think this is a great pattern for how we can abstract some of our major app components into their own silos. I really love the way the tests came together. I fixed them by adding the Logger in the "Link Binary With Libraries" build phase in the Unit Tests target. 

I can run the Logger tests by selecting the Logger scheme in Xcode. They don't run when I run the old Unit Tests target. I think I like this, because unless I change the Logger package I don't need to spend time running those tests. However it doesn't look like Github Actions are running the new Logger tests. Could you update `.github/workflows/main.yml` so that they do? Also I turned on code coverage reports, random test order, and parallel execution for the Logger tests. You managed to get 70% coverage of the logger package!

Also I see your Domain/Delivery/Infrastructure pattern, but I'm not sure I understand what sorts of things go in the Infrastructure folder. Is there a blog post or something that explains this pattern? Maybe that would be another good thing to include in the ADR.

2022-02-16 18:04 UTC, martindsq commented on Logger/Sources/Domain/Services/LoggerServiceAdapter.swift
> +class LoggerServiceAdapter: LoggerService {
Added a comment on this class, and mainly on Log class in the Delivery folder

2022-02-16 18:05 UTC, martindsq commented on Resources/Settings.bundle/Acknowledgements.plist
> -		<dict>
Added CocoaLumberjack back to the Acknolwedgements

2022-02-16 18:05 UTC, martindsq commented on Logger/README.md
> +A description of this package.
Added a README

2022-02-16 18:06 UTC, martindsq commented on Architecture/0005-add-logger-module
> +- No impact in performance is expected.
Wrote some consequences

2022-02-17 15:31 UTC, mplorentz approved these changes
This looks great! I am reading the articles you sent on IDD and liking them. I want to discuss your vision there more in the coming days, but I don't think we need to wait on that to merge this.

2022-02-17 16:04 UTC, merged