Add year to dates in the notification page
planetary-social/planetary-ios pull request #560
Opened 2022-05-17 04:30 UTC by jyu1129

For issue #551
![Screenshot 2022-05-17 at 12 28 52 PM](https://user-images.githubusercontent.com/52351920/168729257-dc37f6c9-63b4-43f9-a22b-38ed7af7917a.png)

2022-05-17 04:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/planetary-social/planetary-ios?pullRequest=560) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/planetary-social/planetary-ios?pullRequest=560) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/planetary-social/planetary-ios?pullRequest=560) it.</sub>

2022-05-17 14:07 UTC, mplorentz requested changes
Thank you for the contribution @jyu1129! Would you mind adding a comma after the day field?

2022-05-17 14:07 UTC, mplorentz commented on Shared/Extensions/Date+Elapsed.swift
> +            formatter.dateFormat = "MMMM dd YYYY"
```suggestion
            formatter.dateFormat = "MMMM dd, YYYY"
```

2022-05-18 03:18 UTC, jyu1129 commented on Shared/Extensions/Date+Elapsed.swift
> +            formatter.dateFormat = "MMMM dd YYYY"
Sure thing!

2022-05-18 16:03 UTC, merged