Make it more clear that Text.post is the verb form of the word
planetary-social/planetary-ios pull request #867
Opened 2022-09-27 14:40 UTC by mplorentz

Changed in response to a question on Crowdin.

2022-09-27 19:26 UTC, martindsq requested changes

2022-09-28 14:07 UTC, mplorentz commented on Source/Localization/es-UY.lproj/Generated.strings
> -"Text.post" = "Publicar";
Are you able to translate those?

2022-09-28 14:08 UTC, mplorentz commented on Source/Localization/es-UY.lproj/Generated.strings
> -"Text.post" = "Publicar";
Oh wait, I can just use the translation we had before.

2022-09-28 14:11 UTC, mplorentz commented on Source/Localization/es-UY.lproj/Generated.strings
> -"Text.post" = "Publicar";
Fixed. Hopefully Crowdin is happy with these.

2022-10-06 19:31 UTC, martindsq approved these changes

2022-10-06 21:04 UTC, merged